name: "Playground addon"
description: "HTTP & WebSocket Proxy to access HomeAssistant without exposing local ports"
version: "1.0.3"
url: "https://github.com/rluvaton/home-assistant-playground-addon"
slug: "playground_addon"

# Disabling the Docker default system init as we use dumb-init instead
init: false

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

ports:
  3000/tcp: 3000

# Access the home assistant API (check again if needed)
auth_api: true
stdin: true
